import { SubtitleTrack } from "../types";

// Mock subtitle data for demonstration (based on https://www.youtube.com/watch?v=pXktHVUpXUc)
const MOCK_SUBTITLES: SubtitleTrack[] = [
  {
    id: 'en-auto',
    language: 'English (Auto-generated)',
    isAutoGenerated: true,
    subtitles: [
      { id: '1', start: 0.5, duration: 3.5, text: "Artificial intelligence is no longer a distant dream." },
      { id: '2', start: 4.5, duration: 4.0, text: "It's here, and it's transforming every aspect of our lives." },
      { id: '3', start: 9.0, duration: 3.5, text: "From healthcare to finance, the impact is profound." },
      { id: '4', start: 13.0, duration: 4.5, text: "But what does the future hold for 2024 and beyond?" },
      { id: '5', start: 18.0, duration: 4.0, text: "We are seeing unprecedented growth in generative models." },
      { id: '6', start: 22.5, duration: 3.5, text: "These systems are learning to create like humans." },
    ]
  },
  {
    id: 'zh-hans',
    language: 'Chinese (Simplified)',
    isAutoGenerated: false,
    subtitles: [
      { id: '1', start: 0.5, duration: 3.5, text: "人工智能不再是一个遥远的梦想。" },
      { id: '2', start: 4.5, duration: 4.0, text: "它就在这里，正在改变我们生活的方方面面。" },
      { id: '3', start: 9.0, duration: 3.5, text: "从医疗保健到金融，影响是深远的。" },
      { id: '4', start: 13.0, duration: 4.5, text: "但 2024 年及以后的未来会怎样？" },
      { id: '5', start: 18.0, duration: 4.0, text: "我们正看到生成式模型的空前增长。" },
      { id: '6', start: 22.5, duration: 3.5, text: "这些系统正在学习像人类一样创造。" },
    ]
  }
];

export async function fetchSubtitleTracks(videoId: string): Promise<SubtitleTrack[]> {
  // In a real extension, we would fetch from YouTube API
  console.log(`Fetching subtitles for video: ${videoId}`);
  return new Promise((resolve) => {
    setTimeout(() => resolve(MOCK_SUBTITLES), 500);
  });
}
