/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect, useRef } from 'react';
import { Controls } from './components/Controls';
import { SubtitleList } from './components/SubtitleList';
import { SubtitleTrack, TTSSettings } from './types';
import { ttsManager } from './lib/tts';
import { Youtube, Zap } from 'lucide-react';
import { addMessageListener, sendMessage } from './lib/messaging';

export default function App() {
  const [currentTime, setCurrentTime] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [tracks, setTracks] = useState<any[]>([]);
  const [selectedTrackId, setSelectedTrackId] = useState<string>('');
  const [currentVideoId, setCurrentVideoId] = useState<string | null>(null);
  const [voices, setVoices] = useState<SpeechSynthesisVoice[]>([]);
  const [isDark, setIsDark] = useState(false);
  const [settings, setSettings] = useState<TTSSettings>(() => {
    const saved = localStorage.getItem('vidpilot_settings');
    if (saved) {
      try {
        return JSON.parse(saved);
      } catch (e) {
        console.error('Failed to parse saved settings', e);
      }
    }
    return {
      engine: 'edge',
      voice: '',
      rate: 1.0,
      pitch: 1.0,
      volume: 1.0,
      autoSync: true,
      playbackRate: 1.0,
      showOverlay: true,
      overlayOpacity: 0.8,
      overlaySize: 24,
      showPopupList: false,
    };
  });

  const lastSubtitleId = useRef<string | null>(null);

  useEffect(() => {
    const cleanup = addMessageListener((message) => {
      const { type, videoId, tracks: ytTracks, subtitles: ytSubtitles, isPlaying: ytIsPlaying, currentTime: ytTime, playbackRate, isDark: ytIsDark } = message;
      
      if (type === 'YOUTUBE_STATE_SYNC') {
        if (ytIsPlaying !== undefined) setIsPlaying(ytIsPlaying);
        if (ytTime !== undefined) setCurrentTime(ytTime);
        if (playbackRate !== undefined) setSettings(s => ({ ...s, playbackRate }));
      }

      if (type === 'YOUTUBE_TRACKS_FOUND' && ytTracks && videoId) {
        setCurrentVideoId(videoId);
        setTracks(ytTracks);
        
        // Auto-select logic:
        // 1. Try to find a Chinese track
        // 2. If not found, find an auto-generated track (usually English) and use it for auto-translation
        const zhTrack = ytTracks.find((t: any) => t.language.includes('Chinese') || t.id.includes('zh'));
        const autoTrack = ytTracks.find((t: any) => t.isAutoGenerated);
        const firstTrack = ytTracks[0];

        const trackToSelect = zhTrack || autoTrack || firstTrack;
        if (trackToSelect) {
          setSelectedTrackId(trackToSelect.id);
          
          // If it's an auto-generated track and not Chinese, we'll request translation to Chinese
          const needsTranslation = !trackToSelect.language.includes('Chinese') && !trackToSelect.id.includes('zh');
          
          sendMessage({
            type: 'FETCH_YOUTUBE_SUBTITLES',
            baseUrl: trackToSelect.baseUrl,
            videoId,
            tlang: needsTranslation ? 'zh-Hans' : undefined
          });
        }
      }

      if (type === 'YOUTUBE_SUBTITLES_LOADED' && ytSubtitles && videoId === currentVideoId) {
        setTracks(prev => {
          if (prev.length === 0) {
            // If no tracks yet, create a default one
            const defaultTrack = {
              id: 'intercepted',
              language: 'Auto Detected',
              subtitles: ytSubtitles,
              isAutoGenerated: true
            };
            setSelectedTrackId('intercepted');
            return [defaultTrack];
          }
          return prev.map(t => 
            t.id === selectedTrackId || prev.length === 1 ? { ...t, subtitles: ytSubtitles } : t
          );
        });
      }

      if (type === 'YOUTUBE_THEME_CHANGE' && ytIsDark !== undefined) {
        setIsDark(ytIsDark);
      }
    });

    // Clear cache when popup is closed (simulated by cleanup)
    return () => {
      cleanup();
      sendMessage({ type: 'CLEAR_SUBTITLE_CACHE' });
    };
  }, [selectedTrackId, currentVideoId]);

  useEffect(() => {
    const loadVoices = () => {
      const availableVoices = window.speechSynthesis.getVoices();
      setVoices(availableVoices);
      if (availableVoices.length > 0 && !settings.voice) {
        const preferred = availableVoices.find(v => 
          v.name.toLowerCase().includes('xiaoxiao') || 
          v.name.toLowerCase().includes('microsoft xiaoxiao')
        ) || availableVoices[0];
        setSettings(s => ({ ...s, voice: preferred.name }));
      }
    };
    loadVoices();
    window.speechSynthesis.onvoiceschanged = loadVoices;
  }, [settings.voice]);

  useEffect(() => {
    const currentTrack = tracks.find(t => t.id === selectedTrackId);
    if (!currentTrack || !currentTrack.subtitles) return;
    
    const activeSubtitle = currentTrack.subtitles.find(
      (sub: any) => currentTime >= sub.start && currentTime < sub.start + sub.duration
    );
    
    // Update overlay
    sendMessage({
      type: 'DUB_SUBTITLE_UPDATE',
      text: activeSubtitle?.text || '',
      settings: {
        showOverlay: settings.showOverlay,
        overlayOpacity: settings.overlayOpacity,
        overlaySize: settings.overlaySize
      }
    });

    if (isPlaying && activeSubtitle && activeSubtitle.id !== lastSubtitleId.current) {
      lastSubtitleId.current = activeSubtitle.id;
      ttsManager.speak(activeSubtitle, settings);
    } else if (!activeSubtitle) {
      lastSubtitleId.current = null;
    }
  }, [currentTime, isPlaying, selectedTrackId, tracks, settings]);

  const saveSettings = () => {
    localStorage.setItem('vidpilot_settings', JSON.stringify(settings));
    localStorage.setItem('vidpilot_track_id', selectedTrackId);
    alert('设置已保存 (Settings saved)');
  };

  const refreshSubtitles = () => {
    sendMessage({ type: 'REFRESH_CAPTIONS' });
  };

  const selectedTrack = tracks.find(t => t.id === selectedTrackId);

  return (
    <div className={`w-full max-h-[600px] overflow-y-auto custom-scrollbar ${isDark ? 'bg-[#0f0f0f]' : 'bg-[#f8f9fb]'} flex flex-col py-4 px-4 transition-colors duration-300`}>
      <div className="w-full space-y-4">
        {/* Compact Header */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 bg-blue-600 rounded-lg flex items-center justify-center shadow-lg shadow-blue-500/20">
              <Zap className="text-white" size={14} />
            </div>
            <h1 className={`text-lg font-bold ${isDark ? 'text-white' : 'text-gray-900'} tracking-tight`}>DubSync</h1>
          </div>
          <div className="flex items-center gap-2">
            <button 
              onClick={refreshSubtitles}
              className={`p-1.5 rounded-full hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors ${isDark ? 'text-gray-400' : 'text-gray-500'}`}
              title="刷新字幕 (Refresh Subtitles)"
            >
              <Youtube size={14} />
            </button>
            <div className="flex items-center gap-2 bg-gray-100 dark:bg-gray-800 px-2 py-1 rounded-full">
              <div className={`w-1.5 h-1.5 rounded-full ${isPlaying ? 'bg-green-500 animate-pulse' : 'bg-amber-500'}`} />
              <span className={`text-[9px] font-bold ${isDark ? 'text-gray-400' : 'text-gray-500'} uppercase tracking-tighter`}>
                {isPlaying ? '正在同步 (Syncing)' : '视频已暂停 (Paused)'}
              </span>
            </div>
          </div>
        </div>

        <div className="space-y-4">
          {/* Controls Area */}
          <Controls 
            settings={settings}
            onSettingsChange={setSettings}
            voices={voices}
            tracks={tracks}
            selectedTrackId={selectedTrackId}
            onTrackChange={setSelectedTrackId}
            onSave={saveSettings}
            isDark={isDark}
          />

          {/* Subtitle List Area - Conditional */}
          {settings.showPopupList && (
            <div className={`${isDark ? 'bg-[#1e1e1e] border-gray-800' : 'bg-white border-gray-200'} border rounded-xl p-3 shadow-sm`}>
              <div className="flex items-center gap-2 text-gray-400 mb-3">
                <Youtube size={12} />
                <span className="text-[9px] font-bold uppercase tracking-widest">实时字幕流</span>
              </div>
              <SubtitleList 
                subtitles={selectedTrack?.subtitles || []}
                currentTime={currentTime}
                isDark={isDark}
              />
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
