/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect, useRef } from 'react';
import { Controls } from './components/Controls';
import { SubtitleList } from './components/SubtitleList';
import { SubtitleTrack, TTSSettings } from './types';
import { ttsManager } from './lib/tts';
import { Youtube, Zap } from 'lucide-react';
import { addMessageListener, sendMessage } from './lib/messaging';

export default function App() {
  const [currentTime, setCurrentTime] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [tracks, setTracks] = useState<any[]>([]);
  const [selectedTrackId, setSelectedTrackId] = useState<string>('');
  const [currentVideoId, setCurrentVideoId] = useState<string | null>(null);
  const [voices, setVoices] = useState<any[]>([]);
  const [isDark, setIsDark] = useState(() => 
    window.matchMedia('(prefers-color-scheme: dark)').matches
  );
  const [settings, setSettings] = useState<TTSSettings>(() => {
    const saved = localStorage.getItem('vidpilot_settings');
    if (saved) {
      try {
        return JSON.parse(saved);
      } catch (e) {
        console.error('Failed to parse saved settings', e);
      }
    }
    return {
      engine: 'edge',
      voice: 'yunjian',
      pitch: 1.0,
      volume: 1.0,
      autoSync: true,
      playbackRate: 1.0,
      showOverlay: true,
      overlayOpacity: 0.8,
      overlaySize: 24,
      showPopupList: true,
      muteOriginal: true,
    };
  });

  const lastSubtitleId = useRef<string | null>(null);
  const lastSubtitleRate = useRef<number>(1.0);

  useEffect(() => {
    sendMessage({ type: 'REFRESH_CAPTIONS' });
  }, []);

  useEffect(() => {
    document.documentElement.classList.toggle('dark', isDark);
  }, [isDark]);

  useEffect(() => {
    const cleanup = addMessageListener((message) => {
      const { type, videoId, tracks: ytTracks, subtitles: ytSubtitles, isPlaying: ytIsPlaying, currentTime: ytTime, playbackRate, isDark: ytIsDark } = message;
      
      if (type === 'YOUTUBE_STATE_SYNC') {
        if (ytIsPlaying !== undefined) setIsPlaying(ytIsPlaying);
        if (ytTime !== undefined) setCurrentTime(ytTime);
        if (playbackRate !== undefined) setSettings(s => ({ ...s, playbackRate }));
      }

      if (type === 'YOUTUBE_TRACKS_FOUND' && ytTracks && videoId) {
        setCurrentVideoId(videoId);
        setTracks(prev => {
          if (currentVideoId === videoId) {
            return ytTracks.map((newTrack: any) => {
              const oldTrack = prev.find(t => t.id === newTrack.id);
              return oldTrack ? { ...newTrack, subtitles: oldTrack.subtitles } : newTrack;
            });
          }
          return ytTracks;
        });
        
        // Priority: 1. Existing Chinese track, 2. Auto-generated track (to be translated), 3. First available
        const zhTrack = ytTracks.find((t: any) => t.language.toLowerCase().includes('chinese') || t.id.includes('zh'));
        const autoTrack = ytTracks.find((t: any) => t.isAutoGenerated);
        const firstTrack = ytTracks[0];

        const trackToSelect = zhTrack || autoTrack || firstTrack;
        
        if (trackToSelect && (!selectedTrackId || currentVideoId !== videoId)) {
          setSelectedTrackId(trackToSelect.id);
          
          const isChinese = trackToSelect.language.toLowerCase().includes('chinese') || trackToSelect.id.includes('zh');
          
          if (!isChinese) {
            // If not Chinese, we request a translation to Chinese (Simplified)
            sendMessage({
              type: 'FETCH_YOUTUBE_SUBTITLES',
              baseUrl: trackToSelect.baseUrl,
              videoId,
              tlang: 'zh-Hans'
            });
          } else {
            sendMessage({
              type: 'FETCH_YOUTUBE_SUBTITLES',
              baseUrl: trackToSelect.baseUrl,
              videoId
            });
          }
        }
      }

      if (type === 'YOUTUBE_SUBTITLES_LOADED' && ytSubtitles && videoId === currentVideoId) {
        setTracks(prev => {
          const newTracks = prev.length === 0 
            ? [{ id: 'intercepted', language: '中文 (简体)', subtitles: ytSubtitles, isAutoGenerated: true }]
            : prev.map(t => {
                if (t.id === selectedTrackId || prev.length === 1) {
                  // If we loaded subtitles for this track, and it's not Chinese, 
                  // it means we translated it. Update the label.
                  const isChinese = t.language.toLowerCase().includes('chinese') || t.id.includes('zh');
                  return { 
                    ...t, 
                    subtitles: ytSubtitles,
                    language: isChinese ? t.language : '中文 (简体) [翻译]'
                  };
                }
                return t;
              });
          
          if (prev.length === 0) setSelectedTrackId('intercepted');
          
          // Trigger pre-fetch
          ttsManager.prefetch(ytSubtitles, settings);
          
          return newTracks;
        });
      }

      if (type === 'YOUTUBE_THEME_CHANGE' && ytIsDark !== undefined) {
        setIsDark(ytIsDark);
      }
    });

    return () => {
      cleanup();
      ttsManager.clearCache();
      sendMessage({ type: 'CLEAR_SUBTITLE_CACHE' });
    };
  }, [selectedTrackId, currentVideoId, settings]);

  useEffect(() => {
    if (typeof window === 'undefined' || !('speechSynthesis' in window)) return;

    const loadVoices = () => {
      const browserVoices = window.speechSynthesis.getVoices();
      if (!browserVoices || browserVoices.length === 0) return;

      const voiceOptions = browserVoices.map(voice => ({
        name: voice.name,
        displayName: `${voice.name} (${voice.lang})`
      }));

      setVoices(voiceOptions);
      setSettings(prev => {
        if (prev.voice && voiceOptions.some(v => v.name === prev.voice)) {
          return prev;
        }
        const yunjianVoice = voiceOptions.find(v => v.name.toLowerCase().includes('yunjian') || v.displayName.toLowerCase().includes('yunjian'));
        if (yunjianVoice) {
          return { ...prev, voice: yunjianVoice.name };
        }
        const defaultVoice = voiceOptions.find(v => v.displayName.toLowerCase().includes('zh')) || voiceOptions[0];
        return { ...prev, voice: defaultVoice?.name || '' };
      });
    };

    loadVoices();
    window.speechSynthesis.addEventListener('voiceschanged', loadVoices);
    return () => {
      window.speechSynthesis.removeEventListener('voiceschanged', loadVoices);
    };
  }, []);

  useEffect(() => {
    const currentTrack = tracks.find(t => t.id === selectedTrackId);
    if (!currentTrack || !currentTrack.subtitles) return;
    
    const activeSubtitle = currentTrack.subtitles.find(
      (sub: any) => currentTime >= sub.start && currentTime < sub.start + sub.duration
    );
    
    sendMessage({
      type: 'DUB_SUBTITLE_UPDATE',
      text: activeSubtitle?.text || '',
      settings: {
        showOverlay: settings.showOverlay,
        overlayOpacity: settings.overlayOpacity,
        overlaySize: settings.overlaySize
      }
    });

    if (!isPlaying) {
      ttsManager.stop();
      lastSubtitleId.current = null;
      return;
    }

    if (activeSubtitle) {
      const isNewSubtitle = activeSubtitle.id !== lastSubtitleId.current;
      const rateChanged = !isNewSubtitle && settings.playbackRate !== lastSubtitleRate.current;

      if (isNewSubtitle || rateChanged) {
        if (isNewSubtitle) {
          lastSubtitleId.current = activeSubtitle.id;
        }

        lastSubtitleRate.current = settings.playbackRate;

        // Record actual start time when the current subtitle is newly activated
        if (isNewSubtitle) {
          setTracks(prev => prev.map(t => {
            if (t.id === selectedTrackId) {
              return {
                ...t,
                subtitles: t.subtitles.map(s => 
                  s.id === activeSubtitle.id ? { ...s, actualStartTime: currentTime } : s
                )
              };
            }
            return t;
          }));
        }

        const activeIndex = currentTrack.subtitles.findIndex((sub: any) => sub.id === activeSubtitle.id);
        const nextSubtitle = activeIndex >= 0 ? currentTrack.subtitles[activeIndex + 1] : null;
        let adjustedRate: number | undefined;

        if (settings.autoSync && nextSubtitle) {
          const subtitleEnd = activeSubtitle.start + activeSubtitle.duration;
          const timeToNextStart = nextSubtitle.start - currentTime;
          const remainingSchedule = subtitleEnd - currentTime;

          if (subtitleEnd > nextSubtitle.start && timeToNextStart > 0 && remainingSchedule > 0) {
            const overlap = subtitleEnd - nextSubtitle.start;
            const speedFactor = 1 + overlap / Math.max(0.1, remainingSchedule);
            adjustedRate = Math.min(2, settings.playbackRate * speedFactor);
          } else if (subtitleEnd > nextSubtitle.start && timeToNextStart <= 0) {
            adjustedRate = 2;
          }
        }

        if (rateChanged) {
          ttsManager.stop();
        }
        ttsManager.speak(activeSubtitle, settings, adjustedRate);
      }
    } else {
      lastSubtitleId.current = null;
      ttsManager.stop();
    }
  }, [currentTime, isPlaying, selectedTrackId, tracks, settings]);

  useEffect(() => {
    const currentTrack = tracks.find(t => t.id === selectedTrackId);
    const hasSubtitles = currentTrack && currentTrack.subtitles && currentTrack.subtitles.length > 0;
    
    if (hasSubtitles && settings.muteOriginal) {
      sendMessage({ type: 'SET_YOUTUBE_MUTE', muted: true });
    } else {
      sendMessage({ type: 'SET_YOUTUBE_MUTE', muted: false });
    }
    
    return () => {
      if (settings.muteOriginal) {
        sendMessage({ type: 'SET_YOUTUBE_MUTE', muted: false });
      }
    };
  }, [selectedTrackId, settings.muteOriginal, tracks]);

  const saveSettings = () => {
    localStorage.setItem('vidpilot_settings', JSON.stringify(settings));
    localStorage.setItem('vidpilot_track_id', selectedTrackId);
    alert('设置已保存 (Settings saved)');
  };

  const refreshSubtitles = () => {
    sendMessage({ type: 'REFRESH_CAPTIONS' });
  };

  const selectedTrack = tracks.find(t => t.id === selectedTrackId);

  return (
    <div className={`w-full h-screen overflow-hidden flex flex-col py-4 px-4 transition-colors duration-300`}>
      <div className="flex-1 flex flex-col min-h-0 space-y-4">
        {/* Compact Header */}
        <div className="flex items-center justify-between shrink-0">
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 bg-blue-600 rounded-lg flex items-center justify-center shadow-lg shadow-blue-500/20">
              <Zap className="text-white" size={14} />
            </div>
            <h1 className={`text-lg font-bold ${isDark ? 'text-white' : 'text-gray-900'} tracking-tight`}>DubSync</h1>
          </div>
          <div className="flex items-center gap-2">
            <button 
              onClick={refreshSubtitles}
              className={`p-1.5 rounded-full hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors ${isDark ? 'text-gray-400' : 'text-gray-500'}`}
              title="刷新字幕 (Refresh Subtitles)"
            >
              <Youtube size={14} />
            </button>
            <div className="flex items-center gap-2 bg-gray-100 dark:bg-gray-800 px-2 py-1 rounded-full">
              <div className={`w-1.5 h-1.5 rounded-full ${isPlaying ? 'bg-green-500 animate-pulse' : 'bg-amber-500'}`} />
              <span className={`text-[9px] font-bold ${isDark ? 'text-gray-400' : 'text-gray-500'} uppercase tracking-tighter`}>
                {isPlaying ? '正在同步 (Syncing)' : '视频已暂停 (Paused)'}
              </span>
            </div>
          </div>
        </div>

        <div className="flex-1 flex flex-col min-h-0 space-y-4 overflow-y-auto custom-scrollbar pr-1">
          {/* Controls Area */}
          <Controls 
            settings={settings}
            onSettingsChange={setSettings}
            voices={voices}
            tracks={tracks}
            selectedTrackId={selectedTrackId}
            onTrackChange={setSelectedTrackId}
            onSave={saveSettings}
            isDark={isDark}
          />

          {/* Subtitle List Area - Conditional */}
          {settings.showPopupList && (
            <div className={`flex-1 min-h-[200px] flex flex-col ${isDark ? 'bg-[#1e1e1e] border-gray-800' : 'bg-white border-gray-200'} border rounded-xl shadow-sm overflow-hidden`}>
              <div className={`flex items-center justify-between px-3 py-2 border-b shrink-0 ${isDark ? 'border-gray-800 bg-[#252525]' : 'border-gray-100 bg-gray-50'}`}>
                <div className="flex items-center gap-2 text-gray-400">
                  <Youtube size={12} />
                  <span className="text-[9px] font-bold uppercase tracking-widest">实时字幕流</span>
                </div>
                {selectedTrack && (
                  <span className={`text-[9px] font-medium ${isDark ? 'text-gray-500' : 'text-gray-400'}`}>
                    {selectedTrack.language}
                  </span>
                )}
              </div>
              <div className="flex-1 overflow-hidden p-3">
                <SubtitleList 
                  subtitles={selectedTrack?.subtitles || []}
                  currentTime={currentTime}
                  isDark={isDark}
                />
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
