import { sendMessage } from './lib/messaging';

let videoElement: HTMLVideoElement | null = null;
let subtitleOverlay: HTMLDivElement | null = null;
let currentSettings: any = { showOverlay: true, overlayOpacity: 0.8, overlaySize: 24 };
let currentVideoId: string | null = null;

// Cache for subtitles (max 10 videos)
const subtitleCache: Map<string, any[]> = new Map();

function createOverlay() {
  if (subtitleOverlay && document.contains(subtitleOverlay)) return;
  
  const old = document.getElementById('dubsync-subtitle-overlay');
  if (old) old.remove();

  subtitleOverlay = document.createElement('div');
  subtitleOverlay.id = 'dubsync-subtitle-overlay';
  Object.assign(subtitleOverlay.style, {
    position: 'absolute',
    bottom: '15%',
    left: '50%',
    transform: 'translateX(-50%)',
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    color: 'white',
    padding: '12px 24px',
    borderRadius: '12px',
    fontSize: '28px',
    fontWeight: '900',
    textAlign: 'center',
    zIndex: '2147483647',
    pointerEvents: 'none',
    display: 'none',
    maxWidth: '90%',
    textShadow: '0 2px 4px rgba(0,0,0,0.9)',
    transition: 'all 0.15s ease-out',
    fontFamily: '"YouTube Sans", Roboto, Arial, sans-serif',
    lineHeight: '1.2',
    letterSpacing: '-0.01em'
  });
  
  const container = document.querySelector('.html5-video-container') || 
                    document.querySelector('#movie_player') || 
                    document.body;
  container.appendChild(subtitleOverlay);
}

function updateOverlay(text: string, settings?: any) {
  if (settings) currentSettings = settings;
  if (!subtitleOverlay) createOverlay();
  if (subtitleOverlay) {
    subtitleOverlay.innerText = text;
    subtitleOverlay.style.display = (currentSettings.showOverlay && text) ? 'block' : 'none';
    subtitleOverlay.style.fontSize = `${currentSettings.overlaySize || 24}px`;
    subtitleOverlay.style.backgroundColor = `rgba(0, 0, 0, ${currentSettings.overlayOpacity || 0.8})`;
  }
}

function getYoutubeCaptions() {
  const urlParams = new URLSearchParams(window.location.search);
  const videoId = urlParams.get('v');
  if (!videoId) return;
  
  currentVideoId = videoId;

  try {
    const scripts = Array.from(document.getElementsByTagName('script'));
    // Look for ytInitialPlayerResponse in script tags
    const playerScript = scripts.find(s => s.innerText.includes('ytInitialPlayerResponse'));
    if (!playerScript) return;

    // More flexible regex to match ytInitialPlayerResponse
    const match = playerScript.innerText.match(/ytInitialPlayerResponse\s*=\s*({.+?});/);
    if (!match) {
      // Try another format
      const match2 = playerScript.innerText.match(/ytInitialPlayerResponse\s*=\s*({.+?})\s*;/);
      if (!match2) return;
    }

    const jsonStr = match ? match[1] : playerScript.innerText.match(/ytInitialPlayerResponse\s*=\s*({.+?})\s*;/)?.[1];
    if (!jsonStr) return;

    const data = JSON.parse(jsonStr);
    const captionTracks = data?.captions?.playerCaptionsTracklistRenderer?.captionTracks || [];
    
    if (captionTracks.length > 0) {
      sendMessage({
        type: 'YOUTUBE_TRACKS_FOUND',
        videoId,
        tracks: captionTracks.map((t: any) => ({
          id: t.vssId,
          language: t.name.simpleText,
          baseUrl: t.baseUrl,
          isAutoGenerated: t.vssId.startsWith('a.')
        }))
      });
    }
  } catch (e) {
    console.error('DubSync: Failed to extract YouTube captions', e);
  }
}

async function fetchTrackContent(baseUrl: string, videoId: string, tlang?: string) {
  const cacheKey = `${videoId}_${tlang || 'original'}`;
  if (subtitleCache.has(cacheKey)) {
    sendMessage({
      type: 'YOUTUBE_SUBTITLES_LOADED',
      videoId,
      subtitles: subtitleCache.get(cacheKey)
    });
    return;
  }

  try {
    let url = `${baseUrl}&fmt=json3`;
    if (tlang) {
      url += `&tlang=${tlang}`;
    }

    const response = await fetch(url);
    const data = await response.json();
    const events = data.events || [];
    
    const subtitles = events
      .filter((e: any) => e.segs)
      .map((e: any, index: number) => ({
        id: `${videoId}_${index}`,
        start: e.tStartMs / 1000,
        duration: e.dDurationMs / 1000,
        text: e.segs.map((s: any) => s.utf8).join(' ').trim()
      }));

    // Manage cache (max 10)
    if (subtitleCache.size >= 10) {
      const firstKey = subtitleCache.keys().next().value;
      subtitleCache.delete(firstKey);
    }
    subtitleCache.set(cacheKey, subtitles);

    sendMessage({
      type: 'YOUTUBE_SUBTITLES_LOADED',
      videoId,
      subtitles
    });
  } catch (e) {
    console.error('DubSync: Failed to fetch track content', e);
  }
}

function findVideo() {
  const video = document.querySelector('video');
  if (video && video !== videoElement) {
    videoElement = video;
    setupListeners();
    createOverlay();
    getYoutubeCaptions();
  }
}

function setupListeners() {
  if (!videoElement) return;

  const syncState = () => {
    if (!videoElement) return;
    sendMessage({
      type: 'YOUTUBE_STATE_SYNC',
      isPlaying: !videoElement.paused,
      currentTime: videoElement.currentTime,
      playbackRate: videoElement.playbackRate
    });
  };

  videoElement.addEventListener('play', syncState);
  videoElement.addEventListener('pause', syncState);
  videoElement.addEventListener('ratechange', syncState);
  videoElement.addEventListener('timeupdate', syncState);
  
  // Initial sync
  syncState();
}

function detectTheme() {
  const isDark = document.documentElement.hasAttribute('dark') || 
                 document.body.classList.contains('dark') ||
                 window.matchMedia('(prefers-color-scheme: dark)').matches;
  
  if (sidePanel) {
    sidePanel.classList.toggle('dark', isDark);
  }

  sendMessage({
    type: 'YOUTUBE_THEME_CHANGE',
    isDark
  });
}

// Initial search
findVideo();
detectTheme();
createUI();
injectInterceptor();
setInterval(monitorTimedText, 3000);

let floatingBall: HTMLDivElement | null = null;
let sidePanel: HTMLDivElement | null = null;
let isPanelOpen = false;

function createUI() {
  if (document.getElementById('dubsync-container')) return;

  const container = document.createElement('div');
  container.id = 'dubsync-container';
  document.body.appendChild(container);

  const shadow = container.attachShadow({ mode: 'open' });

  // Add styles to shadow DOM
  const style = document.createElement('style');
  style.textContent = `
    :host {
      all: initial;
      font-family: system-ui, -apple-system, sans-serif;
    }
    #floating-ball {
      position: fixed;
      right: 30px;
      top: 400px;
      width: 56px;
      height: 56px;
      background: #2563eb;
      border-radius: 50%;
      cursor: move;
      z-index: 999999;
      display: flex;
      align-items: center;
      justify-content: center;
      box-shadow: 0 8px 24px rgba(37, 99, 235, 0.4);
      transition: transform 0.3s cubic-bezier(0.4, 0, 0.2, 1);
      user-select: none;
      border: 2px solid rgba(255, 255, 255, 0.2);
    }
    #floating-ball:hover {
      background: #1d4ed8;
      box-shadow: 0 12px 32px rgba(37, 99, 235, 0.5);
    }
    #floating-ball:active {
      transform: scale(0.95);
    }
    #floating-ball svg {
      width: 28px;
      height: 28px;
      color: white;
    }
    #side-panel {
      position: fixed;
      right: -420px;
      top: 20px;
      width: 400px;
      height: calc(100vh - 40px);
      background: white;
      z-index: 999998;
      box-shadow: -8px 0 32px rgba(0,0,0,0.15);
      transition: right 0.4s cubic-bezier(0.4, 0, 0.2, 1);
      display: flex;
      flex-direction: column;
      overflow: hidden;
      border-radius: 24px 0 0 24px;
    }
    #side-panel.open {
      right: 0;
    }
    #panel-iframe {
      width: 100%;
      height: 100%;
      border: none;
    }
    .dark #side-panel {
      background: #0f0f0f;
      color: white;
    }
  `;
  shadow.appendChild(style);

  // Create Floating Ball
  floatingBall = document.createElement('div');
  floatingBall.id = 'floating-ball';
  floatingBall.innerHTML = `
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
      <path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"></path>
    </svg>
  `;
  shadow.appendChild(floatingBall);

  // Create Side Panel
  sidePanel = document.createElement('div');
  sidePanel.id = 'side-panel';
  const iframe = document.createElement('iframe');
  iframe.id = 'panel-iframe';
  // Use the extension's popup page as the source for the iframe
  iframe.src = chrome.runtime.getURL('index.html');
  sidePanel.appendChild(iframe);
  shadow.appendChild(sidePanel);

  // Dragging logic
  let isDragging = false;
  let startY = 0;
  let startTop = 0;

  floatingBall.addEventListener('mousedown', (e) => {
    isDragging = false;
    startY = e.clientY;
    startTop = floatingBall!.offsetTop;
    
    const onMouseMove = (moveEvent: MouseEvent) => {
      if (Math.abs(moveEvent.clientY - startY) > 5) {
        isDragging = true;
      }
      const newTop = startTop + (moveEvent.clientY - startY);
      floatingBall!.style.top = `${newTop}px`;
    };

    const onMouseUp = () => {
      document.removeEventListener('mousemove', onMouseMove);
      document.removeEventListener('mouseup', onMouseUp);
      
      if (!isDragging) {
        togglePanel();
      }
    };

    document.addEventListener('mousemove', onMouseMove);
    document.addEventListener('mouseup', onMouseUp);
  });

  function togglePanel() {
    isPanelOpen = !isPanelOpen;
    sidePanel?.classList.toggle('open', isPanelOpen);
    if (isPanelOpen) {
      floatingBall?.style.setProperty('transform', 'translateX(-380px)');
    } else {
      floatingBall?.style.setProperty('transform', 'translateX(0)');
    }
  }
}

// Intercept timedtext API parameters by monitoring script tags and global variables
function monitorTimedText() {
  // YouTube often stores caption info in ytInitialPlayerResponse
  const player = document.getElementById('movie_player') as any;
  if (player && player.getOptions) {
    try {
      const captionTracks = player.getOptions('captions')?.captionTracks;
      if (captionTracks && captionTracks.length > 0) {
        sendMessage({
          type: 'YOUTUBE_TRACKS_FOUND',
          videoId: currentVideoId,
          tracks: captionTracks.map((t: any) => ({
            id: t.vss_id,
            language: t.name.simpleText || t.languageCode,
            baseUrl: t.baseUrl,
            isAutoGenerated: t.kind === 'asr'
          }))
        });
      } else {
        // Fallback: If no tracks found, try to click the caption button to trigger loading
        const captionBtn = document.querySelector('.ytp-subtitles-button') as HTMLElement;
        if (captionBtn && captionBtn.getAttribute('aria-pressed') === 'false') {
          console.log('DubSync: No tracks found, attempting to trigger captions by clicking button');
          captionBtn.click();
        }
      }
    } catch (e) {}
  }
}

// Inject a script to intercept network requests (fetch/XHR)
function injectInterceptor() {
  const script = document.createElement('script');
  script.textContent = `
    (function() {
      const originalFetch = window.fetch;
      window.fetch = async (...args) => {
        const response = await originalFetch(...args);
        const url = args[0] instanceof Request ? args[0].url : args[0];
        if (url.includes('youtube.com/api/timedtext')) {
          const clone = response.clone();
          const text = await clone.text();
          window.postMessage({ type: 'TIMEDTEXT_INTERCEPTED', url, text }, '*');
        }
        return response;
      };

      const originalOpen = XMLHttpRequest.prototype.open;
      XMLHttpRequest.prototype.open = function(method, url) {
        this.addEventListener('load', function() {
          if (url.includes('youtube.com/api/timedtext')) {
            window.postMessage({ type: 'TIMEDTEXT_INTERCEPTED', url, text: this.responseText }, '*');
          }
        });
        return originalOpen.apply(this, arguments);
      };
    })();
  `;
  (document.head || document.documentElement).appendChild(script);
}

// Watch for navigation and video changes
const observer = new MutationObserver(() => {
  const urlParams = new URLSearchParams(window.location.search);
  const videoId = urlParams.get('v');
  
  if (videoId && videoId !== currentVideoId) {
    currentVideoId = videoId;
    findVideo();
    getYoutubeCaptions();
    createUI();
  } else if (!videoElement) {
    findVideo();
  }
  detectTheme();
});

observer.observe(document.body, { childList: true, subtree: true });

// Listen for messages from the popup/UI
window.addEventListener('message', (event) => {
  if (event.data.type === 'TIMEDTEXT_INTERCEPTED') {
    const { url, text } = event.data;
    const urlObj = new URL(url);
    const videoId = urlObj.searchParams.get('v');
    
    if (videoId && text) {
      try {
        let subtitles: any[] = [];
        if (text.startsWith('{')) {
          // JSON format
          const data = JSON.parse(text);
          subtitles = data.events
            .filter((e: any) => e.segs)
            .map((e: any, index: number) => ({
              id: `${videoId}-${index}`,
              start: e.tStartMs / 1000,
              duration: e.dDurationMs / 1000,
              text: e.segs.map((s: any) => s.utf8).join('')
            }));
        } else {
          // XML format
          const parser = new DOMParser();
          const xmlDoc = parser.parseFromString(text, "text/xml");
          const textNodes = xmlDoc.getElementsByTagName('text');
          subtitles = Array.from(textNodes).map((node, index) => ({
            id: `${videoId}-${index}`,
            start: parseFloat(node.getAttribute('start') || '0'),
            duration: parseFloat(node.getAttribute('dur') || '0'),
            text: node.textContent || ''
          }));
        }

        if (subtitles.length > 0) {
          console.log('DubSync: Successfully parsed intercepted subtitles', subtitles.length);
          sendMessage({
            type: 'YOUTUBE_SUBTITLES_LOADED',
            videoId,
            subtitles
          });
          // Cache it
          subtitleCache.set(videoId, subtitles);
        }
      } catch (e) {
        console.error('DubSync: Error parsing intercepted timedtext', e);
      }
    }
  }
  if (event.data.type === 'SET_YOUTUBE_RATE' && videoElement) {
    videoElement.playbackRate = event.data.rate;
  }
  if (event.data.type === 'DUB_SUBTITLE_UPDATE') {
    updateOverlay(event.data.text, event.data.settings);
  }
  if (event.data.type === 'FETCH_YOUTUBE_SUBTITLES') {
    fetchTrackContent(event.data.baseUrl, event.data.videoId, event.data.tlang);
  }
  if (event.data.type === 'CLEAR_SUBTITLE_CACHE') {
    subtitleCache.clear();
  }
  if (event.data.type === 'REFRESH_CAPTIONS') {
    getYoutubeCaptions();
  }
});

// Also listen for chrome messages if in extension
if (typeof chrome !== 'undefined' && chrome.runtime && chrome.runtime.onMessage) {
  chrome.runtime.onMessage.addListener((message) => {
    if (message.type === 'SET_YOUTUBE_RATE' && videoElement) {
      videoElement.playbackRate = message.rate;
    }
    if (message.type === 'DUB_SUBTITLE_UPDATE') {
      updateOverlay(message.text, message.settings);
    }
    if (message.type === 'FETCH_YOUTUBE_SUBTITLES') {
      fetchTrackContent(message.baseUrl, message.videoId, message.tlang);
    }
    if (message.type === 'CLEAR_SUBTITLE_CACHE') {
      subtitleCache.clear();
    }
    if (message.type === 'REFRESH_CAPTIONS') {
      getYoutubeCaptions();
    }
    return true;
  });
}

// Clear cache on close (simulated by listening for beforeunload)
window.addEventListener('beforeunload', () => {
  subtitleCache.clear();
});
