/**
 * Content script for YouTube integration
 */

let videoElement: HTMLVideoElement | null = null;
let subtitleOverlay: HTMLDivElement | null = null;
let currentSettings: any = { showOverlay: true, overlayOpacity: 0.8, overlaySize: 24 };

function createOverlay() {
  if (subtitleOverlay && document.contains(subtitleOverlay)) return;
  
  // Remove old one if it exists but is detached
  const old = document.getElementById('dubsync-subtitle-overlay');
  if (old) old.remove();

  subtitleOverlay = document.createElement('div');
  subtitleOverlay.id = 'dubsync-subtitle-overlay';
  Object.assign(subtitleOverlay.style, {
    position: 'absolute',
    bottom: '15%',
    left: '50%',
    transform: 'translateX(-50%)',
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    color: 'white',
    padding: '12px 24px',
    borderRadius: '12px',
    fontSize: '28px',
    fontWeight: '900',
    textAlign: 'center',
    zIndex: '2147483647', // Max z-index
    pointerEvents: 'none',
    display: 'none',
    maxWidth: '90%',
    textShadow: '0 2px 4px rgba(0,0,0,0.9)',
    transition: 'all 0.15s ease-out',
    fontFamily: '"YouTube Sans", Roboto, Arial, sans-serif',
    lineHeight: '1.2',
    letterSpacing: '-0.01em'
  });
  
  // Try to find the best container (YouTube's movie player)
  const container = document.querySelector('.html5-video-container') || 
                    document.querySelector('#movie_player') || 
                    document.body;
  container.appendChild(subtitleOverlay);
}

function updateOverlay(text: string, settings?: any) {
  if (settings) currentSettings = settings;
  if (!subtitleOverlay) createOverlay();
  if (subtitleOverlay) {
    subtitleOverlay.innerText = text;
    subtitleOverlay.style.display = (currentSettings.showOverlay && text) ? 'block' : 'none';
    subtitleOverlay.style.fontSize = `${currentSettings.overlaySize || 24}px`;
    subtitleOverlay.style.backgroundColor = `rgba(0, 0, 0, ${currentSettings.overlayOpacity || 0.8})`;
  }
}

function getYoutubeCaptions() {
  try {
    // Try to find the caption tracks in the page's initial data
    const scripts = Array.from(document.getElementsByTagName('script'));
    const playerScript = scripts.find(s => s.innerText.includes('ytInitialPlayerResponse'));
    if (!playerScript) return null;

    const match = playerScript.innerText.match(/ytInitialPlayerResponse\s*=\s*({.+?});/);
    if (!match) return null;

    const data = JSON.parse(match[1]);
    const captionTracks = data?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
    
    if (captionTracks) {
      window.postMessage({
        type: 'YOUTUBE_TRACKS_FOUND',
        tracks: captionTracks.map((t: any) => ({
          id: t.vssId,
          language: t.name.simpleText,
          baseUrl: t.baseUrl,
          isAutoGenerated: t.vssId.startsWith('a.')
        }))
      }, '*');
    }
  } catch (e) {
    console.error('Failed to extract YouTube captions', e);
  }
}

async function fetchTrackContent(baseUrl: string) {
  try {
    const response = await fetch(`${baseUrl}&fmt=json3`);
    const data = await response.json();
    const events = data.events || [];
    
    const subtitles = events
      .filter((e: any) => e.segs)
      .map((e: any, index: number) => ({
        id: String(index),
        start: e.tStartMs / 1000,
        duration: e.dDurationMs / 1000,
        text: e.segs.map((s: any) => s.utf8).join(' ').trim()
      }));

    window.postMessage({
      type: 'YOUTUBE_SUBTITLES_LOADED',
      subtitles
    }, '*');
  } catch (e) {
    console.error('Failed to fetch track content', e);
  }
}

function findVideo() {
  videoElement = document.querySelector('video');
  if (videoElement) {
    setupListeners();
    createOverlay();
    getYoutubeCaptions();
  }
}

function setupListeners() {
  if (!videoElement) return;

  // Sync playback rate changes
  videoElement.addEventListener('ratechange', () => {
    if (videoElement) {
      window.postMessage({
        type: 'YOUTUBE_RATE_CHANGE',
        playbackRate: videoElement.playbackRate
      }, '*');
    }
  });

  // Sync time updates
  videoElement.addEventListener('timeupdate', () => {
    if (videoElement) {
      window.postMessage({
        type: 'YOUTUBE_TIME_UPDATE',
        currentTime: videoElement.currentTime
      }, '*');
    }
  });

  // Sync play/pause
  videoElement.addEventListener('play', () => {
    window.postMessage({ type: 'YOUTUBE_PLAY' }, '*');
  });

  videoElement.addEventListener('pause', () => {
    window.postMessage({ type: 'YOUTUBE_PAUSE' }, '*');
  });
}

function detectTheme() {
  const isDark = document.documentElement.hasAttribute('dark') || 
                 document.body.classList.contains('dark') ||
                 window.matchMedia('(prefers-color-scheme: dark)').matches;
  
  window.postMessage({
    type: 'YOUTUBE_THEME_CHANGE',
    isDark
  }, '*');
}

// Initial search
findVideo();
detectTheme();

// Watch for navigation and theme changes
const observer = new MutationObserver(() => {
  if (!videoElement || !document.contains(videoElement)) {
    findVideo();
  }
  detectTheme();
});

observer.observe(document.body, { childList: true, subtree: true });

// Listen for messages from the popup/UI
window.addEventListener('message', (event) => {
  if (event.data.type === 'SET_YOUTUBE_RATE' && videoElement) {
    videoElement.playbackRate = event.data.rate;
  }
  if (event.data.type === 'DUB_SUBTITLE_UPDATE') {
    updateOverlay(event.data.text, event.data.settings);
  }
  if (event.data.type === 'FETCH_YOUTUBE_SUBTITLES') {
    fetchTrackContent(event.data.baseUrl);
  }
});
