import { sendMessage } from './lib/messaging';

let videoElement: HTMLVideoElement | null = null;
let subtitleOverlay: HTMLDivElement | null = null;
let currentSettings: any = { showOverlay: true, overlayOpacity: 0.8, overlaySize: 24 };
let currentVideoId: string | null = null;

// Cache for subtitles (max 10 videos)
const subtitleCache: Map<string, any[]> = new Map();

function createOverlay() {
  if (subtitleOverlay && document.contains(subtitleOverlay)) return;
  
  const old = document.getElementById('dubsync-subtitle-overlay');
  if (old) old.remove();

  subtitleOverlay = document.createElement('div');
  subtitleOverlay.id = 'dubsync-subtitle-overlay';
  Object.assign(subtitleOverlay.style, {
    position: 'absolute',
    bottom: '15%',
    left: '50%',
    transform: 'translateX(-50%)',
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    color: 'white',
    padding: '12px 24px',
    borderRadius: '12px',
    fontSize: '28px',
    fontWeight: '900',
    textAlign: 'center',
    zIndex: '2147483647',
    pointerEvents: 'none',
    display: 'none',
    maxWidth: '90%',
    textShadow: '0 2px 4px rgba(0,0,0,0.9)',
    transition: 'all 0.15s ease-out',
    fontFamily: '"YouTube Sans", Roboto, Arial, sans-serif',
    lineHeight: '1.2',
    letterSpacing: '-0.01em'
  });
  
  const container = document.querySelector('.html5-video-container') || 
                    document.querySelector('#movie_player') || 
                    document.body;
  container.appendChild(subtitleOverlay);
}

function updateOverlay(text: string, settings?: any) {
  if (settings) currentSettings = settings;
  if (!subtitleOverlay) createOverlay();
  if (subtitleOverlay) {
    subtitleOverlay.innerText = text;
    subtitleOverlay.style.display = (currentSettings.showOverlay && text) ? 'block' : 'none';
    subtitleOverlay.style.fontSize = `${currentSettings.overlaySize || 24}px`;
    subtitleOverlay.style.backgroundColor = `rgba(0, 0, 0, ${currentSettings.overlayOpacity || 0.8})`;
  }
}

function getYoutubeCaptions() {
  const urlParams = new URLSearchParams(window.location.search);
  const videoId = urlParams.get('v');
  if (!videoId) return;
  
  currentVideoId = videoId;

  try {
    const scripts = Array.from(document.getElementsByTagName('script'));
    // Look for ytInitialPlayerResponse in script tags
    const playerScript = scripts.find(s => s.innerText.includes('ytInitialPlayerResponse'));
    if (!playerScript) return;

    // More flexible regex to match ytInitialPlayerResponse
    const match = playerScript.innerText.match(/ytInitialPlayerResponse\s*=\s*({.+?});/);
    if (!match) {
      // Try another format
      const match2 = playerScript.innerText.match(/ytInitialPlayerResponse\s*=\s*({.+?})\s*;/);
      if (!match2) return;
    }

    const jsonStr = match ? match[1] : playerScript.innerText.match(/ytInitialPlayerResponse\s*=\s*({.+?})\s*;/)?.[1];
    if (!jsonStr) return;

    const data = JSON.parse(jsonStr);
    const captionTracks = data?.captions?.playerCaptionsTracklistRenderer?.captionTracks || [];
    
    if (captionTracks.length > 0) {
      sendMessage({
        type: 'YOUTUBE_TRACKS_FOUND',
        videoId,
        tracks: captionTracks.map((t: any) => ({
          id: t.vssId,
          language: t.name.simpleText,
          baseUrl: t.baseUrl,
          isAutoGenerated: t.vssId.startsWith('a.')
        }))
      });
    }
  } catch (e) {
    console.error('DubSync: Failed to extract YouTube captions', e);
  }
}

async function fetchTrackContent(baseUrl: string, videoId: string, tlang?: string) {
  const cacheKey = `${videoId}_${tlang || 'original'}`;
  if (subtitleCache.has(cacheKey)) {
    sendMessage({
      type: 'YOUTUBE_SUBTITLES_LOADED',
      videoId,
      subtitles: subtitleCache.get(cacheKey)
    });
    return;
  }

  try {
    let url = `${baseUrl}&fmt=json3`;
    if (tlang) {
      url += `&tlang=${tlang}`;
    }

    const response = await fetch(url);
    const data = await response.json();
    const events = data.events || [];
    
    const subtitles = events
      .filter((e: any) => e.segs)
      .map((e: any, index: number) => ({
        id: `${videoId}_${index}`,
        start: e.tStartMs / 1000,
        duration: e.dDurationMs / 1000,
        text: e.segs.map((s: any) => s.utf8).join(' ').trim()
      }));

    // Manage cache (max 10)
    if (subtitleCache.size >= 10) {
      const firstKey = subtitleCache.keys().next().value;
      subtitleCache.delete(firstKey);
    }
    subtitleCache.set(cacheKey, subtitles);

    sendMessage({
      type: 'YOUTUBE_SUBTITLES_LOADED',
      videoId,
      subtitles
    });
  } catch (e) {
    console.error('DubSync: Failed to fetch track content', e);
  }
}

function findVideo() {
  const video = document.querySelector('video');
  if (video && video !== videoElement) {
    videoElement = video;
    setupListeners();
    createOverlay();
    getYoutubeCaptions();
  }
}

function setupListeners() {
  if (!videoElement) return;

  const syncState = () => {
    if (!videoElement) return;
    sendMessage({
      type: 'YOUTUBE_STATE_SYNC',
      isPlaying: !videoElement.paused,
      currentTime: videoElement.currentTime,
      playbackRate: videoElement.playbackRate
    });
  };

  videoElement.addEventListener('play', syncState);
  videoElement.addEventListener('pause', syncState);
  videoElement.addEventListener('ratechange', syncState);
  videoElement.addEventListener('timeupdate', syncState);
  
  // Initial sync
  syncState();
}

function detectTheme() {
  const isDark = document.documentElement.hasAttribute('dark') || 
                 document.body.classList.contains('dark') ||
                 window.matchMedia('(prefers-color-scheme: dark)').matches;
  
  sendMessage({
    type: 'YOUTUBE_THEME_CHANGE',
    isDark
  });
}

// Initial search
findVideo();
detectTheme();

// Watch for navigation and video changes
const observer = new MutationObserver(() => {
  const urlParams = new URLSearchParams(window.location.search);
  const videoId = urlParams.get('v');
  
  if (videoId && videoId !== currentVideoId) {
    findVideo();
  } else if (!videoElement) {
    findVideo();
  }
  detectTheme();
});

observer.observe(document.body, { childList: true, subtree: true });

// Listen for messages from the popup/UI
window.addEventListener('message', (event) => {
  if (event.data.type === 'SET_YOUTUBE_RATE' && videoElement) {
    videoElement.playbackRate = event.data.rate;
  }
  if (event.data.type === 'DUB_SUBTITLE_UPDATE') {
    updateOverlay(event.data.text, event.data.settings);
  }
  if (event.data.type === 'FETCH_YOUTUBE_SUBTITLES') {
    fetchTrackContent(event.data.baseUrl, event.data.videoId, event.data.tlang);
  }
  if (event.data.type === 'CLEAR_SUBTITLE_CACHE') {
    subtitleCache.clear();
  }
  if (event.data.type === 'REFRESH_CAPTIONS') {
    getYoutubeCaptions();
  }
});

// Also listen for chrome messages if in extension
if (typeof chrome !== 'undefined' && chrome.runtime && chrome.runtime.onMessage) {
  chrome.runtime.onMessage.addListener((message) => {
    if (message.type === 'SET_YOUTUBE_RATE' && videoElement) {
      videoElement.playbackRate = message.rate;
    }
    if (message.type === 'DUB_SUBTITLE_UPDATE') {
      updateOverlay(message.text, message.settings);
    }
    if (message.type === 'FETCH_YOUTUBE_SUBTITLES') {
      fetchTrackContent(message.baseUrl, message.videoId, message.tlang);
    }
    if (message.type === 'CLEAR_SUBTITLE_CACHE') {
      subtitleCache.clear();
    }
    if (message.type === 'REFRESH_CAPTIONS') {
      getYoutubeCaptions();
    }
    return true;
  });
}

// Clear cache on close (simulated by listening for beforeunload)
window.addEventListener('beforeunload', () => {
  subtitleCache.clear();
});
