export interface Subtitle {
  id: string;
  start: number; // in seconds
  duration: number; // in seconds
  text: string;
}

export interface SubtitleTrack {
  id: string;
  language: string;
  isAutoGenerated: boolean;
  subtitles: Subtitle[];
}

export type TTSEngine = 'chrome' | 'edge';

export interface TTSSettings {
  engine: TTSEngine;
  voice: string;
  rate: number;
  pitch: number;
  volume: number;
  autoSync: boolean; // adjust rate to match duration
  playbackRate: number; // New: match video playback speed
}
