export interface Subtitle {
  id: string;
  start: number; // in seconds
  duration: number; // in seconds
  text: string;
  actualStartTime?: number; // New: record when it actually started playing
}

export interface SubtitleTrack {
  id: string;
  language: string;
  isAutoGenerated: boolean;
  subtitles: Subtitle[];
}

export type TTSEngine = 'chrome' | 'edge';

export interface TTSSettings {
  engine: TTSEngine;
  voice: string;
  pitch: number;
  volume: number;
  autoSync: boolean; // adjust rate to match duration
  playbackRate: number; // match video playback speed
  showOverlay: boolean;
  overlayOpacity: number;
  overlaySize: number;
  showPopupList: boolean;
  muteOriginal: boolean;
}
